spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    show-sql: true

server:
  port: 8082

client:
  urls:
    ms-restaurant: http://localhost:8081

redis:
  server:
    url: redis://localhost:6379