server:
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: elekberovk442@gmail.com
    password: flaq xrys ijyq fbhd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    consumer:
      group-id: restaurant-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: org.example.RestaurantEvent
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false